=== hidratarse/LM-2122/XSD/videoclub2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="videoclub">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="datos_cliente">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre"/>
              <xs:element name="apellido" minOccurs="1" maxOccurs="2"/>
              <xs:element name="DNI">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="tlf">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datos_factura" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="resguardo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="forma_pago">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Tarjeta"/>
                          <xs:enumeration value="Efectivo"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="importe_total"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="compra" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="DVD" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                        <xs:element name="titulo"/>
                        <xs:element name="fecha"/>
                        </xs:sequence>
                        <xs:attribute name="extras">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="si"/>
                                <xs:enumeration value="no"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="CINTA" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="titulo" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="formato" minOccurs="1" maxOccurs="1"/>
                          </xs:sequence>
                          <xs:attribute name="rewind">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="si"/>
                                <xs:enumeration value="no"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="alquiler" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="pelicula" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre"/>
                          <xs:element name="genero"/>
                          <xs:element name="actores">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="nombre_actor" minOccurs="3" maxOccurs="3"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idPelicula" type="xs:ID" use="required"/>
                        <xs:attribute name="valoracion">
                            <xs:simpleType>
                              <xs:restriction base="xs:decimal">
                                <xs:minInclusive value="0"/>
                                <xs:maxInclusive value="10"/>
                                <xs:pattern value="1*[0-9][.][1-9]"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="fecha" type="xs:date"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hidratarse/LM-2122/XSD/videoclub2.xml
<?xml version="1.0" encoding="UTF-8"?>
<videoclub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "videoclub2.xsd">
  <datos_cliente>
    <nombre>Zeke</nombre>
    <apellido>Jägger</apellido>
    <DNI>06033854B</DNI>
    <tlf>626089187</tlf>
  </datos_cliente>
  <datos_factura>
    <resguardo>
    <forma_pago>Tarjeta</forma_pago>
      <importe_total>1000</importe_total>
    </resguardo>
    <compra>
      <DVD extras="no">
        <titulo>American Psycho</titulo>
        <fecha>25/03/2005</fecha>
      </DVD>
      <CINTA rewind="si">
        <titulo>El Rey León</titulo>
        <formato>VHS</formato>
      </CINTA>
    </compra>
    <alquiler fecha="2002-09-24">
      <pelicula idPelicula="A001" valoracion="9.5">
        <nombre>The Batman</nombre>
        <genero>Superheroes</genero>
        <actores>
          <nombre_actor>Robert Pattinson</nombre_actor>
          <nombre_actor>Paul Dano</nombre_actor>
          <nombre_actor>Zoe Kravitz</nombre_actor>
        </actores>
      </pelicula>
    </alquiler>
  </datos_factura>
</videoclub>
