=== hidratarse/LM-2122/DTD/DTD 1/dtd.dtd
<!ELEMENT CD (fecha+, songs+)>
  <!ELEMENT fecha EMPTY>
  <!ATTLIST fecha mes CDATA #IMPLIED
                            dia CDATA #IMPLIED>
  <!ATTLIST CD titulo CDATA #REQUIRED>
  <!ELEMENT songs (song+)>
  <!ELEMENT song (title+, composers+,producers+, publisher+, artists+)>
    <!ATTLIST song length CDATA #REQUIRED
                                  anio CDATA #REQUIRED>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT composers (composer+)>
    <!ELEMENT composer (nombre, apellidos)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT producers (producer+)>
    <!ELEMENT producer (nombre, apellidos)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT artists (artist+)>
    <!ELEMENT artist (#PCDATA)>

=== hidratarse/LM-2122/DTD/DTD 1/PRACTICA1.xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CD SYSTEM "dtd.dtd">
  <CD titulo="Stoney">
  <fecha></fecha>
    <songs>
      <song length="6:20" anio="1978">
        <title>Hot Cop</title>
        <composers>
          <composer>
            <nombre>Henry</nombre>
            <apellidos>Beolo</apellidos>
          </composer>
        </composers>
        <producers>
          <producer>
            <nombre>Jacques</nombre>
            <apellidos>Morali</apellidos>
          </producer>
        </producers>
        <publisher>PolyGram</publisher>
        <artists>
          <artist>Village People</artist>
        </artists>
      </song>
      </songs>
    </CD>
